=== waldirpires/qgk-json-pocs/json-from-schema-poc/v4.ref-validate-dummy/schema-dereferenced.json
{"$schema":"http://json-schema.org/draft-04/schema#","id":"Service.json","title":"Service","description":"A Customer Facing Service.","type":"object","javaType":"com.ericsson.bss.cpi.entity.Service","additionalProperties":false,"properties":{"id":{"$schema":"http://json-schema.org/draft-04/schema#","id":"Id.json","title":"Id","description":"Uniquely identifies a given entity. Although this is system generated, in certain situations, it can be specified as temporary id when creating several entities as part of a single request and one entity needs to refer to another within the same request. After the entities are created, temporary ids are replaced with system generated ones. When specifying temporary ids, it is recommended that a prefix such as \"tmp\" be used, for example: \"tmp0001\".","type":"string","system-generated":true},"href":{"$schema":"http://json-schema.org/draft-04/schema#","id":"Href.json","title":"Href","description":"URI for the given entity. This is a system-generated URI for a given entity. Using this the entity can be separately addressed over Hypermedia.","type":"string","format":"uri","system-generated":true},"externalId":{"$schema":"http://json-schema.org/draft-04/schema#","id":"ExternalId.json","title":"ExternalId","description":"A unique identifier for the entity in an external system or application. The usage of this type is two-fold: It can act as an identifier which is used via a translation table to point to the system-generated identifier or it can act as a client specified unique identifier for a given entity and subsequently used to identify the entity when it is nested within another entity.","type":"string"},"versionNumber":{"type":"string","description":"The version number identifer for this entity. It is equal to the UTC creation timestamp of this version.","system-generated":true},"validFor":{"$schema":"http://json-schema.org/draft-04/schema#","id":"TimePeriod.json","title":"TimePeriod","description":"Captures the start and end date for a given period of time.","type":"object","javaType":"com.ericsson.bss.cpi.entity.TimePeriod","additionalProperties":false,"properties":{"start":{"type":"string","format":"date-time","description":"Start of the time period","system-defaults":true},"end":{"type":"string","format":"date-time","description":"End of the time period","system-defaults":true}},"required":["start"]},"characteristics":{"type":"array","uniqueItems":true,"description":"An array of name value pairs as characteristics","items":{"$schema":"http://json-schema.org/draft-04/schema#","id":"MapElement.json","title":"MapElement","description":"A object consisting of a name as the key and a value. If applicable, it can also indicate a purpose and a unique id for reference.","type":"object","javaType":"com.ericsson.bss.cpi.entity.MapElement","additionalProperties":false,"properties":{"id":{"$schema":"http://json-schema.org/draft-04/schema#","id":"ExternalId.json","title":"ExternalId","description":"A unique identifier for the entity in an external system or application. The usage of this type is two-fold: It can act as an identifier which is used via a translation table to point to the system-generated identifier or it can act as a client specified unique identifier for a given entity and subsequently used to identify the entity when it is nested within another entity.","type":"string"},"purpose":{"type":"string","description":"The purpose of this named value"},"name":{"type":"string","description":"The name associated with value in this pair"},"value":{"description":"The value associated with the name. Can be of any type"}},"required":["name","value"]}},"statuses":{"type":"array","uniqueItems":true,"description":"An array of statuses applicable for this entity along with their validity period.","items":{"$schema":"http://json-schema.org/draft-04/schema#","id":"StatusValue.json","title":"StatusValue","description":"Represents the status of an entity along with its validity period.","type":"object","javaType":"com.ericsson.bss.cpi.entity.StatusValue","additionalProperties":false,"properties":{"status":{"type":"string","description":"The status of the entity. Valid statuses are as per enumeration \"LifeCycleState\".","enum-reference":"LifeCycleState"},"reason":{"type":"string","description":"The reason for this status as per enumeration \"LifeCycleStateReason\".","enum-reference":"LifeCycleStateReason"},"validFor":{"$schema":"http://json-schema.org/draft-04/schema#","id":"TimePeriod.json","title":"TimePeriod","description":"Captures the start and end date for a given period of time.","type":"object","javaType":"com.ericsson.bss.cpi.entity.TimePeriod","additionalProperties":false,"properties":{"start":{"type":"string","format":"date-time","description":"Start of the time period","system-defaults":true},"end":{"type":"string","format":"date-time","description":"End of the time period","system-defaults":true}},"required":["start"]}},"required":["status","reason"]}},"name":{"type":"string","description":"A word, term, or phrase by which the Service is known and distinguished from other services."},"description":{"type":"string","description":"An explanation of what the service is."},"isEnabled":{"type":"boolean","description":"Signifies if this Service has been enabled for use."},"serviceType":{"type":"string","enum":["CF","RF"],"description":"Type of this Service. Either Customer Facing(CF) or Resource Facing(RF)."},"services":{"type":"array","uniqueItems":true,"description":"An array of references to Resource Facing Services linked to this Customer Facing Service.","items":{"type":"string","format":"uri","description":"A reference to a Service. Expressed as a URI."}},"resources":{"type":"array","uniqueItems":true,"description":"An array of references to Resources belonging to this Product.","items":{"type":"string","format":"uri","description":"A reference to a Resource. Expressed as a URI."}}}}

=== waldirpires/qgk-json-pocs/json-from-schema-poc/v4.ref-validate-dummy/1476970725546-Service.json-sample.json
{"id":"incididunt veniam quis","href":"cxEBDsJjtdm5GWMkiuzJJePIwDuCL6RpdVkpb3ogMJNC8sj8Ce-.f9skR.B2OhVPfnCETDoBysdBKUnPFzDxJLZ7vYPHXeG6J","externalId":"ea anim","versionNumber":"dolore amet non tempor aliquip","validFor":{"start":"3083-10-20T10:55:17.709Z","end":"2342-12-18T16:26:16.596Z"},"characteristics":[{"name":"ut incididunt tempor fugiat","value":{"description":"The value associated with the name. Can be of any type"},"id":"laborum aute velit proident consectetur"}],"statuses":[{"status":"irure non anim pariatur exercitation","reason":"adipisicing eiusmod","validFor":{"start":"4839-02-20T06:14:35.762Z"}}],"name":"ex aliquip","description":"ea non","isEnabled":true,"serviceType":"CF","services":["Xj,WdT-xGKhTf","SNDJ,FUiOI,mIJAcmveqnh-mhNKCNeVllVfRx8qo+IiAW26CzOImNSOwVcdqaX8TlV,Az-xM57jvnDr4","yod,TqRqJjk2sL8r0KAp,+axppL5coActyflq44od3lbYrPpL6+WDUULU3PaWiXwiBCg.5OCGRDuW1zvXptiRePsIx-o","JIsO2KIJz,imkuTuK9d1p-3l.-3nSG6F-Z-hiuznE0gGIDYdihx8SZrTQZrCWN3EBz9E-OCbHawXijw,Dl5","z."],"resources":["u1tBOl.8l1VpdS8kaIM4IbMmUGkyIouwL"]}

=== waldirpires/qgk-json-pocs/json-from-schema-poc/v4.ref-validate-dummy/1476988872317-Service.json-sample.json
{"id":"aute sunt consectetur consequat cillum","href":"DR2C+oaOPqL2CFH0W8nq4ci,T","externalId":"tempor exercitation dolor magna est","versionNumber":"proident ","validFor":{"start":"3215-05-07T14:44:17.512Z"},"characteristics":[{"name":"velit labore","value":{"description":"The value associated with the name. Can be of any type"}},{"name":"occaecat Duis dolor","value":{"description":"The value associated with the name. Can be of any type"}},{"name":"anim","value":{"description":"The value associated with the name. Can be of any type"},"purpose":"irure proident laborum in deserunt","id":"Ut consequat ut ullamco"},{"name":"pariatur","value":{"description":"The value associated with the name. Can be of any type"}}],"statuses":[{"status":"laborum dolor commodo do","reason":"ullamco culpa","validFor":{"start":"3642-03-23T13:59:21.937Z"}},{"status":"","reason":"nisi in consequat mollit"},{"status":"ut adipisicing lab","reason":"quis adipisicing anim"}],"name":"nostrud quis pariatur","description":"id Excepteur irure","isEnabled":true,"serviceType":"RF","services":["iZqb,pb7+WP1S.uU1H2KR41N0aZlHY3PngrwVZww.60AMCup7MkUZbIAIo0rvG1r5qETH"],"resources":["jEx-kQ5+8G+1i2VLsFg2idJJzR+P0rbKcfzNu4x5LpAqVsa2GkEMES5i1j7uPkaR+YdU9Eg"]}
